name: Run Python script daily

on:
  schedule:
    # Tous les jours à 6h00 UTC
    - cron: "0 19 * * *"
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout uniquement le dossier nécessaire
      - name: Checkout specific folder
        uses: actions/checkout@v3
        with:
          sparse-checkout: |
            time_planner_kthlink
          sparse-checkout-cone-mode: false

      # 2. Installer Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # 3. Installer les dépendances nécessaires
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests icalendar

      # 4. Exécuter ton script
      - name: Run Python script
        run: python time_planner_kthlink/main.py
